services:
  django-web:
    build: ./app
    container_name: django-web-prod
    command: /app/entrypoint.prod.sh
    env_file:
      - .env.prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./static:/app/staticfiles
      - ./media:/app/media
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "988"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      grobid:
        condition: service_started
    environment:
      - HOST_PROJECT_PATH=${PWD}
    restart: unless-stopped

  mysql:
    container_name: mysql-prod
    image: mysql
    env_file:
      - .env.prod
    volumes:
      - ./mysql_prod/lib:/var/lib/mysql
      - ./mysql_prod/my.cnf:/etc/mysql/my.cnf
    restart: unless-stopped
    ports: []
    healthcheck: # <--- Add this block
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  nginx:
    image: nginx:latest
    container_name: nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./static:/static
    depends_on:
      - django-web
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot-prod
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email 284124@studenti.unimore.it -d paper-snitch.ing.unimore.it --agree-tos --non-interactive

  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew-prod
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  redis:
    image: redis:7-alpine
    container_name: redis-prod
    restart: unless-stopped
    volumes:
      - redis_data:/data

  celery-worker:
    build: ./app
    container_name: celery-worker-prod
    command: celery -A web worker --loglevel=info
    env_file:
      - .env.prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./static:/app/staticfiles
      - ./media:/app/media
    depends_on:
      mysql:
        condition: service_healthy # <--- Changed here
      redis:
        condition: service_started
      grobid:
        condition: service_started
    restart: unless-stopped

  grobid:
    image: grobid/grobid:0.8.2-crf
    container_name: grobid-prod
    init: true
    expose:
      - "8070"
    ulimits:
      core: 0
    restart: unless-stopped

volumes:
  redis_data:
