services:
  django-web-dev:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: django-web-${STACK_SUFFIX:-dev}
    command: /app/entrypoint.dev.sh
    env_file:
      - .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/app
      - ./static_${STACK_SUFFIX:-dev}:/app/staticfiles
      - django-venv-${STACK_SUFFIX:-dev}:/app/.venv
      - ./media_${STACK_SUFFIX:-dev}:/app/media
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${DJANGO_PORT:-8000}:8000"
    depends_on:
      - mysql
      - redis
    environment:
      - UV_CACHE_DIR=/tmp/uv-cache # Cache in /tmp for development
      - PYTHONUNBUFFERED=1
      - HOST_PROJECT_PATH=${PWD}
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - __pycache__/

        - action: rebuild
          path: ./uv.lock

  celery-worker:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: celery-worker-dev
    command: watchfiles "celery -A web worker --loglevel=info"
    env_file:
      - .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/app
      - django-venv:/app/.venv
      - ./media:/app/media
    depends_on:
      - mysql
      - redis
    environment:
      - UV_CACHE_DIR=/tmp/uv-cache
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  mysql:
    container_name: mysql-${STACK_SUFFIX:-dev}
    image: mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./mysql_${STACK_SUFFIX:-dev}/lib:/var/lib/mysql
      - ./mysql_${STACK_SUFFIX:-dev}/.client.cnf:/root/.my.cnf
      - ./mysql_${STACK_SUFFIX:-dev}/my.cnf:/etc/mysql/my.cnf
    env_file:
      - .env.local

  redis:
    image: redis:7-alpine
    container_name: redis-${STACK_SUFFIX:-dev}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data-${STACK_SUFFIX:-dev}:/data
  celery-worker:
    build: ./app
    container_name: celery-worker-${STACK_SUFFIX:-dev}
    command: watchfiles "celery -A web worker --loglevel=info"
    env_file:
      - .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/app
      - django-venv-${STACK_SUFFIX:-dev}:/app/.venv
      - ./media_${STACK_SUFFIX:-dev}:/app/media
    depends_on:
      - mysql
      - redis
    environment:
      - UV_CACHE_DIR=/tmp/uv-cache
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
  grobid:
    image: grobid/grobid:0.8.2-crf
    container_name: grobid-${STACK_SUFFIX:-dev}
    init: true
    ports:
      - "${GROBID_PORT:-8070}:8070"
    ulimits:
      core: 0
    restart: unless-stopped

volumes:
  django-venv-${STACK_SUFFIX:-dev}:
  redis-data-${STACK_SUFFIX:-dev}:
