services:
  django-web:
    build: ./app
    container_name: django-web-prod
    command: /app/entrypoint.prod.sh
    env_file:
      - .env.prod
    volumes:
      - ./static:/app/staticfiles
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    container_name: mysql-prod
    image: mysql
    env_file:
      - .env.prod
    volumes:
      - ./mysql_prod/lib:/var/lib/mysql
      - ./mysql_prod/my.cnf:/etc/mysql/my.cnf
    restart: unless-stopped

    ports: []

  nginx:
    image: nginx:latest
    container_name: nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./static:/static
    depends_on:
      - django-web
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot-prod
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email 284124@studenti.unimore.it -d paper-snitch.ing.unimore.it --agree-tos --non-interactive

  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew-prod
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
