# Generated by Django 5.2.7 on 2026-02-12 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webApp', '0010_alter_paper_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(db_index=True, help_text="Node ID from workflow definition (e.g., 'extract_text')", max_length=255)),
                ('node_type', models.CharField(help_text="Type of task (e.g., 'celery', 'langgraph', 'python')", max_length=100)),
                ('handler', models.CharField(help_text="Handler reference (e.g., 'workflow_engine.tasks.extract_text_task')", max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('claimed', 'Claimed'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('max_retries', models.IntegerField(default=3)),
                ('attempt_count', models.IntegerField(default=0)),
                ('claimed_by', models.CharField(blank=True, help_text='Worker/host that claimed this task', max_length=255, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, help_text='Claim expiration for stale worker detection', null=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('input_data', models.JSONField(default=dict, help_text='Input parameters for this node')),
                ('output_data', models.JSONField(blank=True, default=dict, help_text='Output/results from this node')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Workflow Node',
                'verbose_name_plural': 'Workflow Nodes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text="Unique workflow name (e.g., 'pdf_analysis_pipeline')", max_length=255, unique=True)),
                ('version', models.IntegerField(default=1, help_text='Version number for workflow evolution')),
                ('description', models.TextField(blank=True, null=True)),
                ('dag_structure', models.JSONField(help_text="DAG structure: {'nodes': [...], 'edges': [...]}")),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this workflow can be used for new runs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow Definition',
                'verbose_name_plural': 'Workflow Definitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict, help_text='Additional context data for the log entry')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflow_engine.workflownode')),
            ],
            options={
                'verbose_name': 'Node Log',
                'verbose_name_plural': 'Node Logs',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NodeArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('file', 'File Reference'), ('url', 'URL'), ('inline', 'Inline Data'), ('database', 'Database Record')], max_length=20)),
                ('name', models.CharField(help_text="Artifact name/key (e.g., 'extracted_text', 'pdf_file')", max_length=255)),
                ('file_path', models.CharField(blank=True, help_text='Path to file in media storage', max_length=500, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('inline_data', models.JSONField(blank=True, help_text='Small data stored inline', null=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the artifact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='workflow_engine.workflownode')),
            ],
            options={
                'verbose_name': 'Node Artifact',
                'verbose_name_plural': 'Node Artifacts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LangGraphCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thread_id', models.CharField(db_index=True, max_length=255)),
                ('checkpoint_id', models.CharField(db_index=True, max_length=255)),
                ('checkpoint_data', models.JSONField(help_text='Serialized LangGraph state')),
                ('parent_checkpoint_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langgraph_checkpoints', to='workflow_engine.workflownode')),
            ],
            options={
                'verbose_name': 'LangGraph Checkpoint',
                'verbose_name_plural': 'LangGraph Checkpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('run_number', models.IntegerField(default=1, help_text='Sequential run number for this paper (1, 2, 3...)')),
                ('input_data', models.JSONField(default=dict, help_text='Input parameters for this workflow run')),
                ('output_data', models.JSONField(blank=True, default=dict, help_text='Final output/results from the workflow')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(help_text='The paper being analyzed by this workflow', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='webApp.paper')),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='workflow_engine.workflowdefinition')),
            ],
            options={
                'verbose_name': 'Workflow Run',
                'verbose_name_plural': 'Workflow Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workflownode',
            name='workflow_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflow_engine.workflowrun'),
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['name', 'version'], name='workflow_en_name_867029_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['is_active', 'name'], name='workflow_en_is_acti_1ebb99_idx'),
        ),
        migrations.AddIndex(
            model_name='nodelog',
            index=models.Index(fields=['node', 'timestamp'], name='workflow_en_node_id_7edc63_idx'),
        ),
        migrations.AddIndex(
            model_name='nodelog',
            index=models.Index(fields=['level', 'timestamp'], name='workflow_en_level_74380e_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeartifact',
            index=models.Index(fields=['node', 'name'], name='workflow_en_node_id_de13be_idx'),
        ),
        migrations.AddIndex(
            model_name='langgraphcheckpoint',
            index=models.Index(fields=['thread_id', 'checkpoint_id'], name='workflow_en_thread__228cf5_idx'),
        ),
        migrations.AddIndex(
            model_name='langgraphcheckpoint',
            index=models.Index(fields=['node', 'thread_id'], name='workflow_en_node_id_24a0ba_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['paper', 'status'], name='workflow_en_paper_i_19034c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['status', 'created_at'], name='workflow_en_status_6cce43_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['workflow_definition', 'status'], name='workflow_en_workflo_1acf43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowrun',
            unique_together={('paper', 'run_number')},
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['workflow_run', 'status'], name='workflow_en_workflo_0d25c2_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['status', 'claim_expires_at'], name='workflow_en_status_8c8643_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['node_id', 'workflow_run'], name='workflow_en_node_id_cd6302_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['celery_task_id'], name='workflow_en_celery__a84e90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflownode',
            unique_together={('workflow_run', 'node_id')},
        ),
    ]
