# Generated by Django 5.2.7 on 2026-02-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdefinition',
            name='dag_diagram',
            field=models.ImageField(blank=True, help_text='Auto-generated DAG visualization (PNG)', null=True, upload_to='workflow_diagrams/'),
        ),
    ]
