# Generated by Django 5.2.7 on 2026-02-13 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0011_databaseschema'),
        ('workflow_engine', '0002_workflowdefinition_dag_diagram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowrun',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['paper', 'run_number'], name='workflow_en_paper_i_f4d43f_idx'),
        ),
    ]
