# Generated by Django 5.2.7 on 2026-02-16 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0003_remove_unique_paper_run_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowdefinition',
            name='name',
            field=models.CharField(db_index=True, help_text="Workflow name (e.g., 'pdf_analysis_pipeline')", max_length=255),
        ),
        migrations.AddConstraint(
            model_name='workflowdefinition',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_workflow_name_version'),
        ),
    ]
