# Generated by Django on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0004_alter_workflowdefinition_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownode',
            name='input_tokens',
            field=models.IntegerField(default=0, help_text='Number of input tokens consumed by this node'),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='output_tokens',
            field=models.IntegerField(default=0, help_text='Number of output tokens generated by this node'),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='total_tokens',
            field=models.IntegerField(default=0, help_text='Total tokens (input + output) used by this node'),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='was_cached',
            field=models.BooleanField(default=False, help_text='Whether this node reused cached results and copied token counts from previous execution'),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='total_input_tokens',
            field=models.IntegerField(default=0, help_text='Total input tokens consumed across all nodes in this workflow run'),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='total_output_tokens',
            field=models.IntegerField(default=0, help_text='Total output tokens generated across all nodes in this workflow run'),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='total_tokens',
            field=models.IntegerField(default=0, help_text='Total tokens (input + output) used by this workflow run'),
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['workflow_run', 'was_cached'], name='workflow_e_workflo_cached_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['paper', 'total_tokens'], name='workflow_e_paper_t_tokens_idx'),
        ),
    ]
