# Generated by Django on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0005_add_token_tracking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('ready', 'Ready'),
                    ('claimed', 'Claimed'),
                    ('running', 'Running'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                    ('skipped', 'Skipped'),
                    ('cancelled', 'Cancelled'),
                ],
                db_index=True,
                default='pending',
                max_length=20
            ),
        ),
    ]
