# Generated by Django 5.2.7 on 2026-02-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0006_add_cancelled_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflownode',
            new_name='workflow_en_workflo_88e7a7_idx',
            old_name='workflow_e_workflo_cached_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowrun',
            new_name='workflow_en_paper_i_46d3ec_idx',
            old_name='workflow_e_paper_t_tokens_idx',
        ),
    ]
