# Generated by Django 5.2.7 on 2026-03-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0007_rename_workflow_e_workflo_cached_idx_workflow_en_workflo_88e7a7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='highlighted_pdf',
            field=models.FileField(blank=True, help_text='PDF with highlighted evidence from evaluation criteria', null=True, upload_to='highlighted_pdfs/'),
        ),
    ]
