# Generated by Django 5.2.7 on 2026-03-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0008_workflowrun_highlighted_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowrun',
            name='highlighted_pdf',
        ),
    ]
