# Generated by Django 5.2.7 on 2026-03-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0009_remove_workflowrun_highlighted_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeartifact',
            name='file',
            field=models.FileField(blank=True, help_text='File upload for artifacts (e.g., highlighted PDFs, reports)', null=True, upload_to='workflow_artifacts/'),
        ),
    ]
