# Generated by Django 5.2.7 on 2026-02-02 09:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('html_file', models.FileField(blank=True, null=True, upload_to='htmls/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('conversion_error', models.TextField(blank=True, help_text='Error message if conversion failed', null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#FF0000', help_text='Hex color code', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Order for display')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='annotator.annotationcategory')),
            ],
            options={
                'verbose_name_plural': 'Annotation Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_text', models.TextField()),
                ('html_selector', models.TextField(help_text='CSS selector or XPath for the annotated element')),
                ('position_data', models.JSONField(default=dict, help_text='Stores position and selection data')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='annotator.annotationcategory')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotator.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
