# Generated by Django 5.2.7 on 2026-02-02 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
        ('webApp', '0010_alter_paper_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='paper',
            field=models.OneToOneField(blank=True, help_text='Associated Paper from webApp', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='webApp.paper'),
        ),
    ]
