# Generated by Django 5.2.7 on 2026-02-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_document_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationcategory',
            name='embedding',
            field=models.JSONField(default=dict, help_text='Embedding vector as JSON'),
        ),
    ]
