# Generated by Django 5.2.7 on 2026-02-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_annotationcategory_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='embedding',
            field=models.BinaryField(blank=True, help_text='Embedding vector as binary data', null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='similarity_score',
            field=models.FloatField(blank=True, help_text='Cosine similarity score with category', null=True),
        ),
    ]
