# Generated by Django 5.2.7 on 2026-02-11 

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0004_annotation_embedding_annotation_similarity_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(
                default=1,
                help_text='User who created this annotation',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='annotations',
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
    ]
