# ================================= Build stage ================================
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS builder
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy 
ENV UV_PYTHON_DOWNLOADS=0

WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project --no-dev

COPY . /app

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-dev


# ================================= Final stage ================================
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS final

RUN apt-get update && apt-get install -y \
    git libpq5 docker.io\
    && rm -rf /var/lib/apt/lists/* 
COPY --from=builder /app /app

RUN chmod +x /app/entrypoint.prod.sh /app/entrypoint.dev.sh

# Ensure media directory exists
RUN mkdir -p /app/media /app/staticfiles

ENV PATH="/app/.venv/bin:$PATH"
ENV UV_CACHE_DIR="/home/nonroot/.cache/uv"

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

RUN playwright install-deps && playwright install

WORKDIR /app
EXPOSE 8000

