# Generated by Django 5.2.7 on 2025-11-04 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Conference name')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('website', models.URLField(blank=True, max_length=500, verbose_name='Website')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conferences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Operation type')),
            ],
            options={
                'verbose_name': 'Operations',
                'verbose_name_plural': 'Operations',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('doi', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='DOI')),
                ('abstract', models.TextField(verbose_name='Abstract')),
                ('datasets', models.TextField(blank=True, help_text='Comma-separated dataset names', null=True, verbose_name='Datasets used')),
                ('supp_materials', models.TextField(blank=True, verbose_name='Supplementary materials')),
                ('paper_url', models.URLField(blank=True, max_length=500, verbose_name='Paper URL')),
                ('code_url', models.URLField(blank=True, max_length=500, verbose_name='code URL')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Full paper text')),
                ('reviews', models.TextField(blank=True, null=True, verbose_name='All reviews text')),
                ('author_feedback', models.TextField(blank=True, null=True, verbose_name='Author feedback')),
                ('meta_review', models.TextField(blank=True, null=True, verbose_name='All Meta-reviews text')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='webApp.conference', verbose_name='Conference')),
            ],
            options={
                'verbose_name': 'Paper',
                'verbose_name_plural': 'Papers',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Author name')),
                ('flag', models.BooleanField(default=False)),
                ('papers', models.ManyToManyField(related_name='authors', to='webApp.paper', verbose_name='Paper')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
    ]
