# Generated by Django 5.2.7 on 2025-12-09 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Conference name')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Website')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conferences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Criterion Name')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Criterion Key')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Criterion',
                'verbose_name_plural': 'Criteria',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LLMModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(help_text="Unique identifier for this model configuration (e.g., 'gpt51', 'gemini25_flash')", max_length=50, unique=True, verbose_name='Model Key')),
                ('visual_name', models.CharField(help_text='Human-readable name shown in the UI', max_length=100, verbose_name='Display Name')),
                ('model', models.CharField(help_text="Actual model name used in API calls (e.g., 'gpt-5.1', 'gemini-2.5-flash')", max_length=100, verbose_name='Model Name')),
                ('api_key_env_var', models.CharField(choices=[('OPENAI_API_KEY', 'OpenAI API Key'), ('GEMINI_API_KEY', 'Gemini API Key'), ('BYTEPLUS_API_KEY', 'BytePlus API Key'), ('ANTHROPIC_API_KEY', 'Anthropic API Key')], help_text='Environment variable name containing the API key', max_length=50, verbose_name='API Key Environment Variable')),
                ('base_url', models.URLField(help_text='API base URL for this model', max_length=300, verbose_name='Base URL')),
                ('token_var', models.CharField(help_text="Variable name for tracking token usage (e.g., 'TOTAL_TOKEN_OPENAI')", max_length=100, verbose_name='Token Variable')),
                ('temperature', models.FloatField(default=1.0, help_text='Sampling temperature for the model', verbose_name='Temperature')),
                ('reasoning_effort', models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Reasoning effort level (for OpenAI models)', max_length=20, null=True, verbose_name='Reasoning Effort')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model is available for use', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'LLM Model Configuration',
                'verbose_name_plural': 'LLM Model Configurations',
                'ordering': ['visual_name'],
            },
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Operation type')),
            ],
            options={
                'verbose_name': 'Operations',
                'verbose_name_plural': 'Operations',
            },
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('bug', 'Bug Report'), ('suggestion', 'Suggestion')], default='bug', max_length=20, verbose_name='Report Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('steps_to_reproduce', models.TextField(blank=True, null=True, verbose_name='Steps to Reproduce')),
                ('expected_behavior', models.TextField(blank=True, null=True, verbose_name='Expected Behavior')),
                ('actual_behavior', models.TextField(blank=True, null=True, verbose_name='Actual Behavior')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Priority')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('wont_fix', "Won't Fix")], default='new', max_length=20, verbose_name='Status')),
                ('browser_info', models.CharField(blank=True, max_length=300, null=True, verbose_name='Browser Info')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='bug_screenshots/', verbose_name='Screenshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reporter')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('doi', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='DOI')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Abstract')),
                ('supp_materials', models.FileField(blank=True, null=True, upload_to='supp_materials', verbose_name='Supplementary materials')),
                ('paper_url', models.URLField(blank=True, max_length=500, verbose_name='Paper URL')),
                ('pdf_url', models.URLField(blank=True, max_length=500, verbose_name='PDF URL')),
                ('code_url', models.URLField(blank=True, max_length=500, verbose_name='Code URL')),
                ('authors', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Authors')),
                ('file', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Full paper text')),
                ('code_text', models.TextField(blank=True, null=True, verbose_name='Code text retrieved from the repository')),
                ('reviews', models.TextField(blank=True, null=True, verbose_name='All reviews text')),
                ('author_feedback', models.TextField(blank=True, null=True, verbose_name='Author feedback')),
                ('meta_review', models.TextField(blank=True, null=True, verbose_name='All Meta-reviews text')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update')),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='webApp.conference', verbose_name='Conference')),
            ],
            options={
                'verbose_name': 'Paper',
                'verbose_name_plural': 'Papers',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Dataset name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dataset description')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Dataset URL')),
                ('dimension', models.IntegerField(blank=True, null=True, verbose_name='Dataset dimension (in MB)')),
                ('from_pdf', models.BooleanField(default=False, verbose_name='Dataset got from the PDF')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update')),
                ('papers', models.ManyToManyField(related_name='datasets', to='webApp.paper', verbose_name='Paper datasets')),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='LLM Model Name')),
                ('model_key', models.CharField(max_length=50, verbose_name='Model Key')),
                ('input_tokens', models.IntegerField(blank=True, null=True, verbose_name='Input Tokens')),
                ('output_tokens', models.IntegerField(blank=True, null=True, verbose_name='Output Tokens')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Raw LLM Response')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='webApp.paper', verbose_name='Paper')),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField(verbose_name='Abstract')),
                ('supp_materials', models.TextField(blank=True, null=True, verbose_name='Supplementary materials')),
                ('code_url', models.URLField(blank=True, max_length=500, verbose_name='code URL')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Full paper text')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_papers', to='webApp.paper')),
            ],
            options={
                'verbose_name': 'PDF Paper',
                'verbose_name_plural': 'PDF Papers',
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('model_var', models.CharField(max_length=100, verbose_name='Model Variable Name')),
                ('tokens_used', models.BigIntegerField(default=0, verbose_name='Tokens Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Token Usage',
                'verbose_name_plural': 'Token Usage',
                'ordering': ['-date', 'model_var'],
                'unique_together': {('date', 'model_var')},
            },
        ),
        migrations.CreateModel(
            name='AnalysisCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted', models.TextField(blank=True, null=True, verbose_name='Extracted Information')),
                ('score_explanation', models.TextField(blank=True, null=True, verbose_name='Score Explanation')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Score (0-5)')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_results', to='webApp.analysis', verbose_name='Analysis')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_results', to='webApp.criterion', verbose_name='Criterion')),
            ],
            options={
                'verbose_name': 'Analysis Criterion Result',
                'verbose_name_plural': 'Analysis Criterion Results',
                'unique_together': {('analysis', 'criterion')},
            },
        ),
    ]
