# Generated by Django 5.2.7 on 2025-10-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome tipo')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine visualizzazione')),
            ],
            options={
                'verbose_name': 'Tipo Sezione',
                'verbose_name_plural': 'Tipi Sezione',
                'ordering': ['order', 'name'],
            },
        ),
    ]
