# Generated by Django 5.2.7 on 2025-11-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='supp_materials',
            field=models.TextField(blank=True, null=True, verbose_name='Supplementary materials'),
        ),
    ]
