# Generated by Django 5.2.7 on 2025-12-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmmodelconfig',
            name='reasoning_effort',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('minimal', 'Minimal'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Reasoning effort level (for OpenAI models)', max_length=20, null=True, verbose_name='Reasoning Effort'),
        ),
    ]
