# Generated by Django 5.2.7 on 2025-11-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_alter_paper_supp_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last update'),
        ),
    ]
