# Generated by Django 5.2.7 on 2025-10-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_sectiontype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
