# Generated by Django 5.2.7 on 2025-12-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_alter_llmmodelconfig_reasoning_effort'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='weight',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='Weight'),
        ),
    ]
