# Generated by Django 5.2.7 on 2025-10-27 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_categories_delete_sectiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Conference name')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('website', models.URLField(blank=True, max_length=500, verbose_name='Website')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conferences',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('doi', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='DOI')),
                ('authors', models.TextField(help_text='Comma-separated list of authors', verbose_name='Authors')),
                ('abstract', models.TextField(blank=True, verbose_name='Abstract')),
                ('text', models.TextField(blank=True, verbose_name='Full paper text')),
                ('datasets', models.TextField(blank=True, help_text='Comma-separated dataset names', verbose_name='Datasets used')),
                ('supplementary_materials', models.TextField(blank=True, verbose_name='Supplementary materials')),
                ('pdf_url', models.URLField(blank=True, max_length=500, verbose_name='PDF URL')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('conferences', models.ManyToManyField(blank=True, related_name='papers', to='webApp.conference', verbose_name='Conferences')),
            ],
            options={
                'verbose_name': 'Paper',
                'verbose_name_plural': 'Papers',
            },
        ),
        migrations.CreateModel(
            name='MetaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Meta-review text')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metareviews', to='webApp.paper', verbose_name='Paper')),
            ],
            options={
                'verbose_name': 'Meta-Review',
                'verbose_name_plural': 'Meta-Reviews',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Review text')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='webApp.paper', verbose_name='Paper')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
