# Generated by Django 5.2.7 on 2025-12-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='name',
            field=models.CharField(blank=True, help_text='Name for the prompt template', max_length=100, null=True, verbose_name='Prompt Name'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='template',
            field=models.TextField(blank=True, help_text='The actual prompt template text with placeholders', null=True, verbose_name='Prompt Template'),
        ),
    ]
