# Generated by Django 5.2.7 on 2025-10-28 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_conference_alter_categories_options_paper_metareview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Author name')),
                ('flag', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Operation type')),
            ],
            options={
                'verbose_name': 'Operations',
                'verbose_name_plural': 'Operations',
            },
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='supplementary_materials',
            new_name='suppl_materials',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='conferences',
        ),
        migrations.AddField(
            model_name='paper',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='webApp.conference', verbose_name='Conference'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='text',
            field=models.TextField(verbose_name='Full paper text'),
        ),
        migrations.AddField(
            model_name='author',
            name='papers',
            field=models.ManyToManyField(related_name='authors', to='webApp.paper', verbose_name='Paper'),
        ),
    ]
