# Generated by Django 5.2.7 on 2026-01-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_analysistask'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
