# Generated by Django 5.2.7 on 2026-01-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0007_analysistask_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysiscriterion',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score'),
        ),
    ]
