# Generated by Django 5.2.7 on 2026-01-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0008_alter_analysiscriterion_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmmodelconfig',
            name='api_key_env_var',
            field=models.CharField(choices=[('OPENAI_API_KEY', 'OpenAI API Key'), ('GEMINI_API_KEY', 'Gemini API Key'), ('BYTEPLUS_API_KEY', 'BytePlus API Key'), ('ANTHROPIC_API_KEY', 'Anthropic API Key'), ('MOONSHOT_API_KEY', 'Moonshot API Key')], help_text='Environment variable name containing the API key', max_length=50, verbose_name='API Key Environment Variable'),
        ),
    ]
