# Generated by Django 5.2.7 on 2025-11-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0009_paper_pdf_url_alter_paper_code_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='pdf_file',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='paper',
            name='supp_materials',
            field=models.FileField(blank=True, null=True, upload_to='supp_materials', verbose_name='Supplementary materials'),
        ),
    ]
