# Generated by Django 5.2.7 on 2026-02-13 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0010_alter_paper_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('migration_name', models.CharField(blank=True, max_length=500)),
                ('schema_diagram', models.ImageField(blank=True, null=True, upload_to='schema_diagrams/')),
                ('schema_dot', models.TextField(blank=True, help_text='GraphViz DOT source')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Database Schema',
                'verbose_name_plural': 'Database Schemas',
                'ordering': ['-created_at'],
            },
        ),
    ]
