# Generated by Django 5.2.7 on 2025-11-28 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0010_rename_pdf_file_paper_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Criterion Name')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Criterion Key')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Criterion',
                'verbose_name_plural': 'Criteria',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='LLM Model Name')),
                ('model_key', models.CharField(max_length=50, verbose_name='Model Key')),
                ('input_tokens', models.IntegerField(blank=True, null=True, verbose_name='Input Tokens')),
                ('output_tokens', models.IntegerField(blank=True, null=True, verbose_name='Output Tokens')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Raw LLM Response')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='webApp.paper', verbose_name='Paper')),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted', models.TextField(blank=True, null=True, verbose_name='Extracted Information')),
                ('score_explanation', models.TextField(blank=True, null=True, verbose_name='Score Explanation')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Score (0-5)')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_results', to='webApp.analysis', verbose_name='Analysis')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_results', to='webApp.criterion', verbose_name='Criterion')),
            ],
            options={
                'verbose_name': 'Analysis Criterion Result',
                'verbose_name_plural': 'Analysis Criterion Results',
                'unique_together': {('analysis', 'criterion')},
            },
        ),
    ]
