# Generated by Django 5.2.7 on 2026-02-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0011_databaseschema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFPaper',
        ),
    ]
