# Generated by Django 5.2.7 on 2025-12-02 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0012_analysis_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Bug Title')),
                ('description', models.TextField(verbose_name='Bug Description')),
                ('steps_to_reproduce', models.TextField(blank=True, null=True, verbose_name='Steps to Reproduce')),
                ('expected_behavior', models.TextField(blank=True, null=True, verbose_name='Expected Behavior')),
                ('actual_behavior', models.TextField(blank=True, null=True, verbose_name='Actual Behavior')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Priority')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('wont_fix', "Won't Fix")], default='new', max_length=20, verbose_name='Status')),
                ('browser_info', models.CharField(blank=True, max_length=300, null=True, verbose_name='Browser Info')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='bug_screenshots/', verbose_name='Screenshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reporter')),
            ],
            options={
                'verbose_name': 'Bug Report',
                'verbose_name_plural': 'Bug Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
