# Generated by Django 5.2.7 on 2026-02-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0012_remove_pdfpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores unexpected fields extracted during scraping', null=True, verbose_name='Metadata (unknown/unexpected fields)'),
        ),
    ]
