# Generated by Django 5.2.7 on 2025-12-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0013_bugreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AddField(
            model_name='bugreport',
            name='report_type',
            field=models.CharField(choices=[('bug', 'Bug Report'), ('suggestion', 'Suggestion'), ('improvement', 'Improvement')], default='bug', max_length=20, verbose_name='Report Type'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
