# Generated by Django 5.2.7 on 2026-02-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0013_add_metadata_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload conference logo or icon', null=True, upload_to='conference_logos/', verbose_name='Conference Logo'),
        ),
    ]
