# Generated by Django 5.2.7 on 2025-12-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0014_alter_bugreport_options_bugreport_report_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='report_type',
            field=models.CharField(choices=[('bug', 'Bug Report'), ('suggestion', 'Suggestion')], default='bug', max_length=20, verbose_name='Report Type'),
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('model_var', models.CharField(max_length=100, verbose_name='Model Variable Name')),
                ('tokens_used', models.BigIntegerField(default=0, verbose_name='Tokens Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Token Usage',
                'verbose_name_plural': 'Token Usage',
                'ordering': ['-date', 'model_var'],
                'unique_together': {('date', 'model_var')},
            },
        ),
    ]
