# Generated by Django 5.2.7 on 2026-02-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0014_conference_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Authors'),
        ),
    ]
