# Generated by Django 5.2.7 on 2025-12-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0015_alter_bugreport_report_type_tokenusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(help_text="Unique identifier for this model configuration (e.g., 'gpt51', 'gemini25_flash')", max_length=50, unique=True, verbose_name='Model Key')),
                ('visual_name', models.CharField(help_text='Human-readable name shown in the UI', max_length=100, verbose_name='Display Name')),
                ('model', models.CharField(help_text="Actual model name used in API calls (e.g., 'gpt-5.1', 'gemini-2.5-flash')", max_length=100, verbose_name='Model Name')),
                ('api_key_env_var', models.CharField(choices=[('OPENAI_API_KEY', 'OpenAI API Key'), ('GEMINI_API_KEY', 'Gemini API Key'), ('BYTEPLUS_API_KEY', 'BytePlus API Key'), ('ANTHROPIC_API_KEY', 'Anthropic API Key')], help_text='Environment variable name containing the API key', max_length=50, verbose_name='API Key Environment Variable')),
                ('base_url', models.URLField(help_text='API base URL for this model', max_length=300, verbose_name='Base URL')),
                ('token_var', models.CharField(help_text="Variable name for tracking token usage (e.g., 'TOTAL_TOKEN_OPENAI')", max_length=100, verbose_name='Token Variable')),
                ('temperature', models.FloatField(default=1.0, help_text='Sampling temperature for the model', verbose_name='Temperature')),
                ('thinking_enabled', models.BooleanField(default=False, help_text='Enable thinking mode (for models that support it)', verbose_name='Thinking Enabled')),
                ('reasoning_effort', models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Reasoning effort level (for OpenAI models)', max_length=20, null=True, verbose_name='Reasoning Effort')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model is available for use', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'LLM Model Configuration',
                'verbose_name_plural': 'LLM Model Configurations',
                'ordering': ['visual_name'],
            },
        ),
    ]
