# Generated by Django 5.2.7 on 2026-02-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0015_alter_paper_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'verbose_name': 'Conference', 'verbose_name_plural': 'Conferences'},
        ),
        migrations.RemoveField(
            model_name='conference',
            name='url',
        ),
        migrations.AddField(
            model_name='conference',
            name='acronym',
            field=models.CharField(blank=True, help_text="Short name, e.g., 'MICCAI'", max_length=50, null=True, verbose_name='Acronym'),
        ),
        migrations.AddField(
            model_name='conference',
            name='full_name',
            field=models.CharField(blank=True, help_text="Complete conference name, e.g., 'Medical Image Computing and Computer Assisted Intervention'", max_length=500, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='conference',
            name='papers_url',
            field=models.URLField(blank=True, help_text='URL of the page listing papers', max_length=500, verbose_name='Papers Page URL'),
        ),
        migrations.AddField(
            model_name='conference',
            name='scraping_schema',
            field=models.JSONField(blank=True, help_text='JSON schema for scraping papers from this conference', null=True, verbose_name='Scraping Schema'),
        ),
        migrations.AddField(
            model_name='conference',
            name='website_url',
            field=models.URLField(blank=True, help_text='Main conference website URL', max_length=500, verbose_name='Conference Website'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(help_text="Full display name, e.g., 'MICCAI 2024'", max_length=300, verbose_name='Conference name'),
        ),
    ]
