# Generated by Django 5.2.7 on 2026-02-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0016_alter_conference_options_remove_conference_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['-year', 'acronym'], 'verbose_name': 'Conference', 'verbose_name_plural': 'Conferences'},
        ),
        migrations.AlterUniqueTogether(
            name='conference',
            unique_together={('acronym', 'year')},
        ),
    ]
