# Generated by Django 5.2.7 on 2025-12-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0016_llmmodelconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmmodelconfig',
            name='thinking_enabled',
        ),
        migrations.AddField(
            model_name='paper',
            name='code_text',
            field=models.TextField(blank=True, null=True, verbose_name='Code text retrieved from the repository'),
        ),
    ]
