# Generated by Django 5.2.7 on 2026-02-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0017_alter_conference_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='is_scraping',
            field=models.BooleanField(default=False, help_text='True if scraping is currently running for this conference', verbose_name='Scraping in Progress'),
        ),
        migrations.AddField(
            model_name='conference',
            name='last_scrape_end',
            field=models.DateTimeField(blank=True, help_text='When the last scraping process completed', null=True, verbose_name='Last Scrape End'),
        ),
        migrations.AddField(
            model_name='conference',
            name='last_scrape_start',
            field=models.DateTimeField(blank=True, help_text='When the last scraping process was started', null=True, verbose_name='Last Scrape Start'),
        ),
        migrations.AddField(
            model_name='conference',
            name='last_scrape_status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('running', 'Running')], help_text='Status of the last scraping operation', max_length=50, null=True, verbose_name='Last Scrape Status'),
        ),
        migrations.AddField(
            model_name='conference',
            name='scraping_log_file',
            field=models.CharField(blank=True, help_text='Path to the current/last scraping log file', max_length=500, null=True, verbose_name='Scraping Log File'),
        ),
    ]
