# Generated by Django 5.2.7 on 2026-02-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0018_conference_is_scraping_conference_last_scrape_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='sections',
            field=models.JSONField(blank=True, help_text='Dictionary mapping section names to their content', null=True, verbose_name='Paper sections'),
        ),
    ]
