# Generated by Django 5.2.7 on 2026-02-17 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0019_paper_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='webApp.conference', verbose_name='Conference'),
        ),
    ]
