# Generated by Django 5.2.7 on 2026-02-19 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0021_paper_section_embeddings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='papersectionembedding',
            options={'verbose_name': 'Paper Section Embedding', 'verbose_name_plural': 'Paper Section Embeddings'},
        ),
        migrations.AlterField(
            model_name='papersectionembedding',
            name='embedding_dimension',
            field=models.IntegerField(default=1536, help_text='Dimension of the embedding vector'),
        ),
        migrations.AlterField(
            model_name='papersectionembedding',
            name='embedding_model',
            field=models.CharField(default='text-embedding-3-small', help_text='OpenAI model used for embedding', max_length=50),
        ),
        migrations.AlterField(
            model_name='papersectionembedding',
            name='paper',
            field=models.ForeignKey(help_text='Paper this embedding belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='section_embeddings', to='webApp.paper'),
        ),
        migrations.AlterField(
            model_name='papersectionembedding',
            name='section_type',
            field=models.CharField(help_text='Section type: abstract, introduction, methods, results, discussion, conclusion, etc.', max_length=50),
        ),
    ]
