# Generated by Django 5.2.7 on 2026-02-20 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0022_alter_papersectionembedding_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFileEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_url', models.URLField(help_text='Repository URL for this code version', max_length=500)),
                ('file_path', models.CharField(help_text='Relative path of the file in the repository', max_length=500)),
                ('file_content', models.TextField(help_text='Text content of the file (or chunk for large files)')),
                ('chunk_index', models.IntegerField(default=0, help_text='Chunk index for files split into multiple parts (0 for non-chunked files)')),
                ('total_chunks', models.IntegerField(default=1, help_text='Total number of chunks for this file')),
                ('content_hash', models.CharField(help_text='SHA256 hash of the original file content (for cache invalidation)', max_length=64)),
                ('embedding', models.JSONField(help_text='Vector embedding as JSON array')),
                ('embedding_model', models.CharField(default='text-embedding-3-small', help_text='OpenAI model used for embedding', max_length=50)),
                ('embedding_dimension', models.IntegerField(default=1536, help_text='Dimension of the embedding vector')),
                ('tokens_used', models.IntegerField(default=0, help_text='Number of tokens used for this embedding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(help_text='Paper this code embedding belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='code_file_embeddings', to='webApp.paper')),
            ],
            options={
                'verbose_name': 'Code File Embedding',
                'verbose_name_plural': 'Code File Embeddings',
                'db_table': 'code_file_embeddings',
                'indexes': [models.Index(fields=['paper', 'code_url'], name='idx_paper_code_url'), models.Index(fields=['paper', 'file_path'], name='idx_paper_file_path'), models.Index(fields=['content_hash'], name='idx_content_hash')],
                'constraints': [models.UniqueConstraint(fields=('paper', 'code_url', 'file_path', 'chunk_index', 'embedding_model'), name='unique_code_file_chunk_embedding')],
            },
        ),
    ]
