# Generated by Django 5.2.7 on 2026-02-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0023_codefileembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReproducibilityAspectEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect_id', models.CharField(help_text='Unique identifier for the aspect (e.g., methodology, structure, components)', max_length=50, unique=True)),
                ('aspect_name', models.CharField(help_text='Human-readable name of the aspect', max_length=200)),
                ('aspect_description', models.TextField(help_text='Detailed description of what this aspect analyzes')),
                ('aspect_context', models.TextField(help_text='Full context text used to generate the embedding')),
                ('embedding', models.JSONField(help_text='Vector embedding as JSON array')),
                ('embedding_model', models.CharField(default='text-embedding-3-small', help_text='OpenAI model used for embedding', max_length=50)),
                ('embedding_dimension', models.IntegerField(default=1536, help_text='Dimension of the embedding vector')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reproducibility Aspect Embedding',
                'verbose_name_plural': 'Reproducibility Aspect Embeddings',
                'db_table': 'reproducibility_aspect_embeddings',
                'indexes': [models.Index(fields=['aspect_id'], name='idx_aspect_id')],
            },
        ),
    ]
