# Generated by Django 5.2.7 on 2026-02-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0025_reproducibilitychecklistcriterion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetDocumentationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_id', models.CharField(help_text='Unique identifier (e.g., data_collection_described, annotation_protocol)', max_length=50, unique=True)),
                ('criterion_number', models.IntegerField(help_text='Criterion number (1-10)')),
                ('criterion_name', models.CharField(help_text='Human-readable name of the criterion', max_length=200)),
                ('category', models.CharField(help_text='Category: data_collection, annotation, ethics_availability', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the criterion')),
                ('criterion_context', models.TextField(help_text='Full context text used to generate the embedding')),
                ('embedding', models.JSONField(help_text='Vector embedding as JSON array')),
                ('embedding_model', models.CharField(default='text-embedding-3-small', help_text='OpenAI model used for embedding', max_length=50)),
                ('embedding_dimension', models.IntegerField(default=1536, help_text='Dimension of the embedding vector')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dataset Documentation Criterion',
                'verbose_name_plural': 'Dataset Documentation Criteria',
                'db_table': 'dataset_documentation_criteria',
                'ordering': ['criterion_number'],
                'indexes': [models.Index(fields=['criterion_id'], name='idx_dataset_crit_id'), models.Index(fields=['category'], name='idx_dataset_category')],
            },
        ),
    ]
